---
- name: destroy

  hosts: localhost

  gather_facts: false

  tasks:

    - name: remove docker container
      community.docker.docker_container:
        name: "{{ inventory_hostname }}"

        state: absent
