---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible
    pre_build_image: true
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    tmpfs:
      - /tmp
      - /opt
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - side_effect
    - verify
    - cleanup
    - destroy
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../common/converge.yml
    verify: ../common/verify.yml
    destroy: ../common/destroy.yml
  inventory:
    host_vars:
      instance:
        avideo_debug: true
        avideo_servername: localhost
        avideo_site_title: this_is_a_test
        avideo_tls_certificate: " /etc/ssl/certs/ssl-cert-snakeoil.pem"
        avideo_tls_cert_key: "/etc/ssl/private/ssl-cert-snakeoil.key"
verifier:
  name: ansible
